import { Link } from 'react-router-dom';
import { useAuth } from '@/context/AuthContext';
import { LED, Rivet } from '@/components/primitives/Details';
import { mockDashboardStats, mockDiscoveryFeed, mockMyPostedJugaads, mockMyRequests, mockDashboardNotifications, CATEGORY_COLORS, JUGAAD_STATUS, REQUEST_STATUS, timeAgo, daysUntil } from '@/data/jugaadMockData';
import { Search, Plus, ArrowRight, Bell, ClipboardList, Send, MessageSquare, BriefcaseBusiness, IndianRupee } from 'lucide-react';

export function DashboardHome() {
  const { user, isDemoMode } = useAuth();
  const name = user?.name?.split(' ')[0] || 'there';
  const stats = [
    ['RECOMMENDED', mockDashboardStats.recommendedJugaads, Search, 'amber'],
    ['MY ACTIVE JUGAADS', mockDashboardStats.myActiveJugaads, ClipboardList, 'coral'],
    ['REQUESTS RECEIVED', mockDashboardStats.requestsReceived, Bell, 'amber'],
    ['MY REQUESTS', mockDashboardStats.myRequests, Send, 'mint'],
    ['COLLABORATIONS', mockDashboardStats.activeCollaborations, BriefcaseBusiness, 'mint'],
    ['UNREAD MESSAGES', mockDashboardStats.unreadMessages, MessageSquare, 'coral'],
  ];
  return <div>
    <section className="pt-12 sm:pt-16 pb-8 flex flex-col lg:flex-row lg:items-end justify-between gap-6">
      <div><div className="flex items-center gap-3 mb-4"><LED color="mint" pulse size={7}/><span className="font-technical text-[9px] text-ink-2">01 — YOUR JUGAAD WORKSPACE</span><span className="h-px w-10 bg-metal-2"/><span className="font-technical text-[9px] text-mint">STATUS // ONLINE</span>{isDemoMode && <span className="font-technical text-[7px] text-amber/60 px-2 py-0.5 rounded" style={{border:'1px solid rgba(214,138,60,0.2)',background:'rgba(214,138,60,0.04)'}}>DEMO ACCOUNT</span>}</div><h1 className="font-display text-4xl sm:text-5xl lg:text-6xl tracking-tight">WELCOME,<br/><span className="text-amber">{name.toUpperCase()}.</span></h1><p className="mt-4 max-w-xl text-sm text-ink-2 leading-relaxed">Find the next opportunity, post something you need solved, and make something useful with people on campus.</p></div>
      <div className="surface-wood rounded-xl p-4 min-w-[230px] relative" style={{ transform: 'rotate(1deg)' }}><Rivet size={6} className="absolute top-1.5 left-1.5"/><Rivet size={6} className="absolute top-1.5 right-1.5"/><div className="flex items-center gap-2 mb-2"><span className="grid place-items-center w-8 h-8 rounded-full bg-amber text-bg-0 font-display text-[10px]">{user?.name?.slice(0,2).toUpperCase() || 'U'}</span><div><p className="font-mono text-[10px] text-paper">{user?.name || 'Your workspace'}</p><p className="font-technical text-[7px] text-paper/70">OPERATOR // ACTIVE</p></div></div><div className="flex items-center gap-2"><LED color="mint" pulse size={5}/><span className="font-mono text-[8px] text-paper/80">The room is yours.</span></div></div>
    </section>
    <section className="grid md:grid-cols-2 gap-4 mb-8"><Link to="/dashboard/find-jugaad" className="surface-metal-brushed rounded-2xl p-6 group hover:border-amber/50 transition-all" style={{border:'1px solid rgba(214,138,60,.25)'}}><div className="flex items-start justify-between"><span className="grid place-items-center w-12 h-12 rounded-xl bg-amber/10 text-amber"><Search size={23}/></span><ArrowRight className="text-ink-3 group-hover:text-amber group-hover:translate-x-1 transition-all" size={18}/></div><p className="font-display text-2xl mt-6">FIND A JUGAAD</p><p className="font-mono text-[10px] text-ink-2 mt-2">Opportunities selected for your skills.</p><p className="font-technical text-[8px] text-amber mt-5">{mockDashboardStats.recommendedJugaads} OPEN OPPORTUNITIES →</p></Link><Link to="/dashboard/post-jugaad" className="surface-metal-brushed rounded-2xl p-6 group hover:border-mint/50 transition-all" style={{border:'1px solid rgba(93,184,154,.25)'}}><div className="flex items-start justify-between"><span className="grid place-items-center w-12 h-12 rounded-xl bg-mint/10 text-mint"><Plus size={23}/></span><ArrowRight className="text-ink-3 group-hover:text-mint group-hover:translate-x-1 transition-all" size={18}/></div><p className="font-display text-2xl mt-6">POST A JUGAAD</p><p className="font-mono text-[10px] text-ink-2 mt-2">Ask the campus to help you get it done.</p><p className="font-technical text-[8px] text-mint mt-5">CREATE AN OPPORTUNITY →</p></Link></section>
    <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-2.5 mb-8">{stats.map(([label,value,Icon,color])=><div key={label} className="surface-panel rounded-xl p-3"><div className="flex justify-between items-start"><Icon size={14} className={`text-${color}`}/><span className="font-display text-2xl" style={{color:`var(--${color})`}}>{value}</span></div><p className="font-technical text-[7px] text-ink-3 mt-3">{label}</p></div>)}</section>
    <section className="grid lg:grid-cols-[1.35fr_.65fr] gap-6"><div className="surface-panel rounded-2xl p-5"><div className="flex items-center justify-between mb-4"><div><p className="font-technical text-[9px] text-ink-0">RECOMMENDED FOR YOU</p><p className="font-mono text-[9px] text-ink-3 mt-1">Fresh opportunities matching your campus skills.</p></div><Link to="/dashboard/find-jugaad" className="font-technical text-[8px] text-amber">VIEW ALL →</Link></div><div className="space-y-2.5">{mockDiscoveryFeed.slice(0,3).map((item)=><OpportunityRow key={item.id} item={item}/>)}</div></div><div className="space-y-4"><div className="surface-wood rounded-2xl p-5"><p className="font-technical text-[9px] text-paper/90 mb-4">MY ACTIVE JUGAADS</p>{mockMyPostedJugaads.filter((x)=>!['completed','cancelled'].includes(x.status)).slice(0,3).map((x)=><Link to="/dashboard/my-jugaads" key={x.id} className="flex items-center gap-2.5 py-2 border-b border-paper/10 last:border-0"><span className="w-2 h-2 rounded-full" style={{background:`var(--${JUGAAD_STATUS[x.status].color})`}}/><span className="font-editorial text-sm text-paper flex-1 truncate">{x.title}</span><span className="font-mono text-[8px] text-paper/50">₹{x.amount}</span></Link>)}</div><div className="surface-panel rounded-2xl p-5"><div className="flex justify-between mb-3"><p className="font-technical text-[9px]">RECENT ACTIVITY</p><Bell size={13} className="text-amber"/></div>{mockDashboardNotifications.slice(0,3).map((n)=><Link to={n.conversationId?`/dashboard/messages/${n.conversationId}`:n.jugaadId?.startsWith('JG-1')?'/dashboard/requests':'/dashboard/my-requests'} key={n.id} className="flex gap-2 py-2 border-b border-metal-1/40 last:border-0"><span>{n.emoji}</span><div><p className="font-mono text-[9px] text-ink-1 leading-snug">{n.text}</p><p className="font-mono text-[7px] text-ink-3 mt-1">{timeAgo(n.timestamp)}</p></div></Link>)}</div></div></section>
    <section className="mt-6 flex justify-center gap-3"><Link to="/dashboard/my-requests" className="machine-control machine-control--ghost"><span className="ctrl-led"/>MY REQUESTS ({mockMyRequests.length})</Link><Link to="/dashboard/messages" className="machine-control machine-control--ghost"><span className="ctrl-led"/>MESSAGES</Link></section>
  </div>;
}
function OpportunityRow({item}){return <Link to="/dashboard/find-jugaad" className="flex items-center gap-3 rounded-xl p-3 surface-metal hover:border-amber/30 transition-colors" style={{border:'1px solid var(--metal-1)'}}><span className="grid place-items-center w-10 h-10 rounded-lg shrink-0" style={{background:`color-mix(in srgb, var(--${CATEGORY_COLORS[item.category]}) 15%, transparent)`,color:`var(--${CATEGORY_COLORS[item.category]})`}}><span className="font-display text-sm">{item.category.slice(0,1)}</span></span><div className="min-w-0 flex-1"><p className="font-editorial text-sm text-ink-0 truncate">{item.title}</p><p className="font-mono text-[8px] text-ink-3 mt-1">{item.skillRequired} · {item.poster.name} · {timeAgo(item.postedAt)}</p></div><div className="text-right shrink-0"><p className="font-display text-sm text-amber">₹{item.amount}</p><p className="font-mono text-[8px] text-coral">{daysUntil(item.deadline)}</p></div></Link>}
